-- Initial schema.

CREATE TABLE audit_log_entry
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type       VARCHAR(255)                            NOT NULL,
    wallet_id  VARCHAR(255)                            NOT NULL,
    stock_name VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_audit_log_entry PRIMARY KEY (id)
);

CREATE TABLE bank_stock_holding
(
    stock_name VARCHAR(255) NOT NULL,
    quantity   INTEGER      NOT NULL CHECK (quantity >= 0),
    CONSTRAINT pk_bank_stock_holding PRIMARY KEY (stock_name)
);

CREATE TABLE wallet
(
    id VARCHAR(255) NOT NULL,
    CONSTRAINT pk_wallet PRIMARY KEY (id)
);

CREATE TABLE wallet_stock_holding
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    wallet_id  VARCHAR(255)                            NOT NULL,
    stock_name VARCHAR(255)                            NOT NULL,
    quantity   INTEGER                                 NOT NULL CHECK (quantity >= 0),
    CONSTRAINT pk_wallet_stock_holding PRIMARY KEY (id),
    CONSTRAINT uq_wallet_stock UNIQUE (wallet_id, stock_name),
    CONSTRAINT fk_wallet_stock_wallet
        FOREIGN KEY (wallet_id)
            REFERENCES wallet (id)
            ON DELETE CASCADE
);